# ==============================
# === ERPNext API settings ===
# ==============================
erpnext.api.base-url=http://127.0.0.1:8000/api/resource
erpnext.api.api-key=9aee9f260f54aa2
erpnext.api.api-secret=334a0d6f237b809
erpnext.api.url=http://127.0.0.1:8000
# ==============================
# === Désactiver la base JDBC ===
# ==============================
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# ==============================
# === Thymeleaf settings ===
# ==============================
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
